# Generated by Django 4.2.2 on 2023-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Php', 'Php'), ('AI', 'AI'), ('Node', 'Node'), ('Database', 'Database'), ('Cloud', 'Cloud')], max_length=100),
        ),
    ]
